package com.ofs.ldap.api;

public enum AppErrCode {

	UNKNOWN_ERROR,

	AUTHENTICATION_NOT_SUPPORTED_BY_SERVER,
	USERNAME_PASSWORD_INCORRECT,
	ERROR_TO_CREATE_CONTEXT,

	EMPLOYEE_NUMBER_NOT_FOUND,
	SURNAME_NOT_FOUND,
	COMMONNAME_NOT_FOUND,
	MOBILE_NUMBER_NOT_FOUND
}
